<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>MexanicS.SharedKernel</PackageId>
        <Version>0.1.0</Version>
        <Authors>mexanicS</Authors>
        <Description>Shared error and result primitives for .NET services.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="CSharpFunctionalExtensions" Version="3.7.0" />
      <None Include="README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

</Project>
