services:
  postgres:
    container_name: postgres_directory_service
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
        
  seq:
    image: datalust/seq:latest
    container_name: seq_directory_service
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
        
volumes:
  postgres-data:
    